name: exchange
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  core:
    path: packages/core
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  data:
    path: packages/data
  dio: ^5.4.1
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  net:
    path: packages/net
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  ex_lints:
    path: packages/ex_lints
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  melos: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
