name: core
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  domain:
    path: ../domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  ex_lints:
    path: ../ex_lints
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7

flutter:
