name: net
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.8
  ex_lints:
    path: ../ex_lints
  flutter_test:
    sdk: flutter
